plugin: aws_ec2
replace_dash_in_groups: false
regions:
  - us-east-1
  - us-west-2
keyed_groups:
  - prefix: tag
    key: tags
  - prefix: region
    key: placement.region
    separator: "_"
hostnames:
  - tag:Name
compose:
  ansible_host: tags.Name | lower
  instance_id: instance_id
