#Requires -Version 5.1

<#
.SYNOPSIS
    Resolve an informal AWS account name to its profile, account ID, and SSO session.
.DESCRIPTION
    Reads aws-configs/accounts.json and applies fuzzy matching to resolve names like
    "PLUS" or "SharedServices" to a concrete account object without guessing.

    Match tiers (stops at the first tier that returns >= 1 hit):
      1. Exact name (case-sensitive)
      2. Case-insensitive exact
      3. Normalized nickname match (lowercase + strip spaces/dashes/underscores;
         "pac-prd", "PAC PRD", and "pacprd" all match the same nickname entry)
      4. Case-insensitive substring on name
      5. Token overlap (splits on camel-case/hyphens/underscores)

    Tie-breaking within a tier:
      - Same display name in both orgs: Foundation wins silently (migration target).
      - Multiple different accounts: user is prompted to choose. Use -Quiet to error
        instead of prompting (safe for unattended callers).

    Returns a PSCustomObject: Name, AccountId, Org, SsoSession, Profile.
.PARAMETER Name
    The account name or nickname to resolve (e.g. "PLUS", "PALegacyPlus", "shared").
.PARAMETER Quiet
    Error instead of prompting when multiple accounts match equally. Use in scripts
    that cannot accept stdin.
.EXAMPLE
    Resolve-AwsAccount.ps1 -Name PLUS
.EXAMPLE
    $acct = Resolve-AwsAccount.ps1 -Name PALegacySharedServices -Quiet
    aws ec2 describe-instances --profile $acct.Profile --region us-east-1
.NOTES
    Requires aws-configs/accounts.json (generated by aws-configs/tools/generate_aws_config.py).
    Run from anywhere — path is resolved relative to this script's location.
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory)]
    [ValidateNotNullOrEmpty()]
    [string] $Name,

    [switch] $Quiet
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# ---------------------------------------------------------------------------
# Load registry
# ---------------------------------------------------------------------------
$registryPath = Join-Path $PSScriptRoot '..\..\aws-configs\accounts.json'
if (-not (Test-Path $registryPath)) {
    Write-Error "accounts.json not found at $registryPath. Run: python aws-configs/tools/generate_aws_config.py"
    exit 1
}

$registry  = Get-Content $registryPath -Raw | ConvertFrom-Json
$accounts  = @($registry.accounts)

# ---------------------------------------------------------------------------
# Matching helpers
# ---------------------------------------------------------------------------
function Get-Normalized([string]$s) {
    ($s.ToLower() -replace '[\s\-_]', '')
}

function Get-Tokens([string]$s) {
    # Split on hyphens, underscores, and camelCase boundaries; always return array
    @($s -csplit '(?<=[a-z])(?=[A-Z])|[-_]' | Where-Object { $_ })
}

function Get-TokenScore([string]$Input, [string]$Candidate) {
    $inputTokens = Get-Tokens $Input.ToLower()
    $candTokens  = Get-Tokens $Candidate.ToLower()
    $hits = @($inputTokens | Where-Object { $candTokens -contains $_ }).Count
    return $hits
}

# ---------------------------------------------------------------------------
# Tier matching — stop at the first tier with >= 1 result
# ---------------------------------------------------------------------------
$candidates = @()

# Tier 1: exact (case-sensitive)
$candidates = @($accounts | Where-Object { $_.name -ceq $Name })

# Tier 2: case-insensitive exact
if ($candidates.Count -eq 0) {
    $candidates = @($accounts | Where-Object { $_.name -ieq $Name })
}

# Tier 3: normalized nickname match
if ($candidates.Count -eq 0) {
    $normInput = Get-Normalized $Name
    $candidates = @($accounts | Where-Object {
        $nicknames = @($_.PSObject.Properties['nicknames'].Value)
        ($nicknames | ForEach-Object { Get-Normalized $_ }) -contains $normInput
    })
}

# Tier 4: substring
if ($candidates.Count -eq 0) {
    $candidates = @($accounts | Where-Object { $_.name -ilike "*$Name*" })
}

# Tier 5: token overlap on name (score >= 1)
if ($candidates.Count -eq 0) {
    $scored = @($accounts | ForEach-Object {
        [PSCustomObject]@{ Account = $_; Score = (Get-TokenScore $Name $_.name) }
    } | Where-Object { $_.Score -ge 1 } | Sort-Object Score -Descending)
    if ($scored.Count -gt 0) {
        $topScore   = $scored[0].Score
        $candidates = @($scored | Where-Object { $_.Score -eq $topScore } | ForEach-Object { $_.Account })
    }
}

# ---------------------------------------------------------------------------
# Zero matches
# ---------------------------------------------------------------------------
if ($candidates.Count -eq 0) {
    # Suggest closest 5 by simple character overlap as a hint
    $suggestions = $accounts | ForEach-Object {
        $common = 0
        foreach ($c in $Name.ToLower().ToCharArray()) { if ($_.name.ToLower().Contains($c)) { $common++ } }
        [PSCustomObject]@{ Name = $_.name; Score = $common }
    } | Sort-Object Score -Descending | Select-Object -First 5 | ForEach-Object { $_.Name }

    Write-Error "No account found matching '$Name'. Did you mean: $($suggestions -join ', ')?"
    exit 1
}

# ---------------------------------------------------------------------------
# Tie-breaking
# ---------------------------------------------------------------------------
$resolved = $null

if ($candidates.Count -eq 1) {
    $resolved = $candidates[0]
}
else {
    # Silent Foundation-over-Legacy: same display name, one Foundation entry, rest are Legacy
    $uniqueNames      = @($candidates | Select-Object -ExpandProperty name -Unique)
    $foundationOnly   = @($candidates | Where-Object { $_.org -eq 'foundation' })
    $legacyOnly       = @($candidates | Where-Object { $_.org -eq 'legacy' })

    if ($uniqueNames.Count -eq 1 -and $foundationOnly.Count -eq 1 -and $legacyOnly.Count -ge 1) {
        # Exactly one Foundation entry for this name — prefer it silently
        $resolved = $foundationOnly[0]
    }
    else {
        # Genuine ambiguity — must prompt (or error in -Quiet mode)
        if ($Quiet) {
            $list = ($candidates | ForEach-Object { "$($_.name) ($($_.org), $($_.accountId))" }) -join '; '
            Write-Error "Multiple accounts match '$Name' and -Quiet was specified. Matches: $list"
            exit 1
        }

        Write-Host ""
        Write-Host "Multiple accounts match '$Name'. Choose one:" -ForegroundColor Cyan
        for ($i = 0; $i -lt $candidates.Count; $i++) {
            $c = $candidates[$i]
            Write-Host ("  [{0}] {1,-40} {2,-12} {3}" -f ($i + 1), $c.name, $c.org, $c.accountId)
        }
        Write-Host ""

        $selection = $null
        while ($null -eq $selection) {
            $raw = Read-Host "Enter number (1-$($candidates.Count))"
            $n   = 0
            if ([int]::TryParse($raw, [ref]$n) -and $n -ge 1 -and $n -le $candidates.Count) {
                $selection = $candidates[$n - 1]
            }
            else {
                Write-Host "  Invalid — enter a number between 1 and $($candidates.Count)." -ForegroundColor Yellow
            }
        }
        $resolved = $selection
    }
}

# ---------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------
[PSCustomObject]@{
    Name       = $resolved.name
    AccountId  = $resolved.accountId
    Org        = $resolved.org
    SsoSession = $resolved.ssoSession
    Profile    = $resolved.profile
}
